FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./
RUN npm install --production

COPY backend/ ./

# Инициализация БД при старте
RUN node init-db.js

EXPOSE 3001

CMD ["node", "server.js"]